### ISSUE TITLE
How to escape links in a text? 

### ISSUE THREAD

**Issue by yangtheman** [dnagir/ruby-haml-js#12]
Hi,

More of a simple question than an issue....

One of the attributes for an object I return is sort of a message (text), and inside the message are a few links like the following. 

`<a href="http://fox.com">Fox</a> jumped over the <a href="http://moon.com">moon</a>`

When I display this in hamljs template like the following, I get the literal text with html tags, instead of text with clickable links. How can I achieve this? 

`%p #{message}`

Thank you so much in advance!

**Comment by dnagir** [comment]
See the [readme of the haml-js](https://github.com/creationix/haml-js/blob/master/README.markdown):

> For interpolation, you may use #{} for escaped interpolation or !{} for unsafe interpolation.
