### ISSUE TITLE
ExecJS::ProgramError: ReferenceError: Can't find variable: console

### ISSUE THREAD

**Issue by Draiken** [dnagir/ruby-haml-js#2]
Here is the template

```
%h1 Errors

%ul#errors
  - errors.each do |error|
    %li= error
```

When I open the file with this template, call `render` on it, this error is raised.

**Comment by dnagir** [comment]
You are using Ruby in JavaScript HAML.
Please use the syntax as described at https://github.com/creationix/haml-js

Here is how you need to write it:

``` haml
%h1 Errors

%ul#errors
  :each error in errors
    %li= error
```

**Comment by Draiken** [comment]
Thank you!

**Comment by dnagir** [comment]
You are welcome.
