### ISSUE TITLE
Configure custom escape option

### ISSUE THREAD

**Issue by shiftb** [dnagir/ruby-haml-js#3]
Is there a way yet to configure the custom escape option that haml-js has?
Right now it's including the default html_escape in every template which isn't optimal.

Thanks for the great library!

**Comment by dnagir** [comment]
It is planned. But I will get my hands onto it next week or so.

How would you like to provide the options? I thought about something like:

``` ruby
RubyHamlJs::Template.custom_escape = "App.escape_html"
```

But not sure if that's the best way.

**Comment by dnagir** [comment]
Or you can submit a pull request. Take this as a baseline: https://github.com/dnagir/pakunok/blob/master/lib/pakunok/haml_js_template.rb#L52

and make sure to write the specs.

**Comment by shiftb** [comment]
Thanks so much!!
