### ISSUE TITLE
How can I  use this with img

### ISSUE THREAD

**Issue by alexandru-calinoiu** [dnagir/ruby-haml-js#6]
Hi,

 I am trying to have something like:

```
%img{:src => cart_image_url}
```

I get an "Unexpected token >" error. Any ideas how I can achive this?

Thanks,

**Comment by dnagir** [comment]
The attribute syntax is a bit different from Ruby HAML. Please see the [haml-js](https://github.com/creationix/haml-js).

What you need to do is:

```
%img{src: cart_image_url}
```

Also keep in mind that you can't access any Ruby stuff there (including URL helpers) since it is a JavaScript runtime.

**Comment by alexandru-calinoiu** [comment]
Thanks,
