### ISSUE TITLE
Malformed attribute blick

### ISSUE THREAD

**Issue by renius** [dnagir/ruby-haml-js#8]
Uncaught Error: ExecJS::ProgramError: Malformed attribute block
  (in /home/anton/work/Perekup.net/app/assets/javascripts/templates/anonym_car.jst.hamljs

ful list of file
.row= car

**Comment by dnagir** [comment]
It looks like it is an issue with the haml-js itself (not the ruby gem). Could you please report it to the [haml-js](https://github.com/creationix/haml-js/) and show the repro?
